default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  username: root
  password: 1234
  socket: /var/run/mysqld/mysqld.sock
  database: ikantam_development

test:
  <<: *default
  username: root
  password: 1234
  socket: /var/run/mysqld/mysqld.sock
  database: ikantam_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
